### ISSUE TITLE
Add nightly link checking

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#366]
Now that we've [removed per commit link checking](https://github.com/medic/cht-docs/issues/367) on PRs, we should add nightly link checking on the entire repo.  This will enable us to catch [link rot](https://en.wikipedia.org/wiki/Link_rot) overtime. In the original link checker effort (see #259), we used `muffet`.  This is still a good tool!  We should just run them [on a schedule](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events) with something like:

```yaml
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # this example runs at 3:15am every day:
    - cron:  '15 3 * * *'
```

What we have right now runs on every push:

```yaml
on:
  push:
    branches:
      - '*' # branch checking is below so all this is one CI file
```

And then we check for if we're on master or not to only run certain parts of the CI workflow:

```yaml
- name: Master Branch Only - Deploy to GH pages
   if: ${{ github.ref == 'refs/heads/master' }}
```

Check out the resulting PR from #367 as that will show what we need to add back in to the nightly runs.

**Comment by mrjones-plip** [comment]
This is what I yanked out of `ci.yml` in #365 :

```yaml

      # Pinning to current version as of Aug 3, 2020 for stability
      - name: All Branches - Install Go v1.14
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      # Pinning to current version as of Aug 3, 2020 for stability
      - name: All Branches - Install Muffet v1.3.3
        run: env GO111MODULE="on" go get github.com/raviqqe/muffet@1.3.3

      # run in background so CI doesn't hang waiting for "ctrl + c".  Sleep so hugo server is ready
      - name: All Branches - Serve Hugo site
        run: |
          hugo server&
          sleep 5

      - name: All Branches - Run Muffet link checker
        shell: bash
        run: ./.github/scripts/muffet.sh
```
